### ISSUE TITLE
ssh: connect to host *** port ***: Operation timed out

### ISSUE THREAD

**Issue by pratikjain227** [marcodallasanta/ssh-scp-deploy#21] opened 2023-05-15 18:43 UTC
This is my workflow file - 
https://github.com/pratikjain227/test-github-actions/blob/main/.github/workflows/generate-and-scp-config.yml

But I am getting the below error - 
`ssh: connect to host *** port ***: Operation timed out
😢 Something went wrong during pre-upload script`

Checked almost everything, but not sure where the issue is.
FYI - I am able to SCP from my local with the secrets added in GitHub.

Any help is appreciated.

**Comment by marcodallasanta** [comment] 2023-05-15 22:07
Hey hi 👋🏼 ,
The action configuration looks syntactically correct, so I'd assume the problem is somewhere else probably in the server or the ssh connection command.

If I were you, I'd do the following to be sure the issue is not in your server configuration:
1. Try if you can connect via ssh from another host to be sure the issue is not accessing via ssh. 
2. If the above works, I'd double check the value you put inside the secrets are correct.
3. I'd also double-check the port you're using to connect since looks like you're getting a timeout.

Let me know if the above helped otherwise, I'll try to come up with something else.

P.s. mockoon is very interesting. I suggest you take a look at [this](https://docs.imposter.sh/), I've found it was more flexible.

**Comment by marcodallasanta** [comment] 2023-05-18 16:23
Closing this one now, feel free to open again if other support is needed.

**Closed as not planned** 2023-05-18 16:23 UTC

**Comment by pratikjain227** [comment] 2023-08-23 07:48
Thanks, it was resolved, I was probably doing something wrong.
I came back here for your suggestion on https://docs.imposter.sh/
